### ISSUE TITLE
Resource keys must be valid C# identifiers

### ISSUE THREAD

**Issue by MarkPflug** [MarkPflug/Elemental.JsonResource#15]
Currently, a key with a space (ie "Greeting Message") will break due to generating invalid code because the key is expected to be a valid C# identifier.

This can be fixed in (at least) one of two ways:

1) Modify the key to be valid be replacing any invalid characters with underscore.

2) Don't generate code for invalid key, and report that the identifier is invalid.

I'm leaning toward the second option, as the first has the potential to cause key conflicts after the replacements occur.

**Comment by earloc** [comment]
The default 'ResX'-generatir has some logic to replace any invalid character with `_`.

Within [TypealizR] (https://github.com/earloc/TypealizR), I implemented a similar approach to deal with this, as well as handling cases where such a name would end up as a duplicate (by just appending an index to it). In case of a duplicate, a warning is emitted.

So I guess there might be a third option: 3 Sanitize key while handling duplicates.
